cd ../../../

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/ngramconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/rs_ngramconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/rsdel_ngramconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/drs_ngramconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/sequential_drs_ngramconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/random_drs_ngramconv_ember_configuration_file.json


