cd ../../../

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/avastconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/rs_avastconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/rsdel_avastconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/drs_avastconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/sequential_drs_avastconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/random_drs_avastconv_ember_configuration_file.json


