cd ../../

python train_end2end_detector.py  configurations/EMBER/training_time/AvastConv/avastconv_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/AvastConv/drs_avastconv_ember_configuration_file_32768_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/AvastConv/drsm_avastconv_ember_configuration_file_12_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/AvastConv/random_drs_avastconv_ember_configuration_file_0.10_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/AvastConv/rs_avastconv_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/AvastConv/rsdel_avastconv_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/AvastConv/sequential_drs_avastconv_ember_configuration_file_0.10.json

python train_end2end_detector.py  configurations/EMBER/training_time/BBDnn/bbdnn_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/BBDnn/drs_bbdnn_ember_configuration_file_32768_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/BBDnn/drsm_bbdnn_ember_configuration_file_12_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/BBDnn/random_drs_bbdnn_ember_configuration_file_0.10_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/BBDnn/rs_bbdnn_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/BBDnn/rsdel_bbdnn_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/BBDnn/sequential_drs_bbdnn_ember_configuration_file_0.10_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training_time/MalConv/drs_malconv_ember_configuration_file_32768_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/MalConv/drsm_malconv_ember_configuration_file_12_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/MalConv/malconv_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/MalConv/random_drs_malconv_ember_configuration_file_0.10_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/MalConv/rs_malconv_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/MalConv/rsdel_malconv_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/MalConv/sequential_drs_malconv_ember_configuration_file_0.10_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training_time/NGramConv/drs_ngramconv_ember_configuration_file_32768_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/NGramConv/drsm_ngramconv_ember_configuration_file_12_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/NGramConv/ngramconv_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/NGramConv/random_drs_ngramconv_ember_configuration_file_0.10_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/NGramConv/rs_ngramconv_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/NGramConv/rsdel_ngramconv_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/NGramConv/sequential_drs_ngramconv_ember_configuration_file_0.10_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training_time/ResNet18/resnet18_ember_configuration_file_pos_weight_0.875.json
python train_end2end_detector.py  configurations/EMBER/training_time/LightGBM/lightgbm_configuration_file_lr_0.05_ff_0.7_bf_0.7_pos_weight_0.875.json

