cd ../../


# AvastConv
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/avastconv_ember_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/avastconv_ember_validation_set_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/avastconv_ember_test_set_configuration_file_pos_weight_0.875.json

# BBDnn
python train_end2end_detector.py  configurations/EMBER/training/BBDnn/bbdnn_ember_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/bbdnn_ember_validation_set_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/bbdnn_ember_test_set_configuration_file_pos_weight_0.875.json

# NGramConv
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/ngramconv_ember_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/ngramconv_ember_validation_set_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/ngramconv_ember_test_set_configuration_file_pos_weight_0.875.json

# MalConv
python train_end2end_detector.py  configurations/EMBER/training/MalConv/malconv_ember_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/malconv_ember_validation_set_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/malconv_ember_test_set_configuration_file_pos_weight_0.875.json



