cd ../../


# AvastConv
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/DRS/drs_avastconv_ember_configuration_file_10244_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/DRS/drs_avastconv_ember_validation_set_configuration_file_10244_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/DRS/drs_avastconv_ember_test_set_configuration_file_10244_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/DRS/drs_avastconv_ember_configuration_file_16384_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/DRS/drs_avastconv_ember_validation_set_configuration_file_16384_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/DRS/drs_avastconv_ember_test_set_configuration_file_16384_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/DRS/drs_avastconv_ember_configuration_file_32768_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/DRS/drs_avastconv_ember_validation_set_configuration_file_32768_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/DRS/drs_avastconv_ember_test_set_configuration_file_32768_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/DRS/drs_avastconv_ember_configuration_file_65536_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/DRS/drs_avastconv_ember_validation_set_configuration_file_65536_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/DRS/drs_avastconv_ember_test_set_configuration_file_65536_weighted_1.2.json


# BBDnn
python train_end2end_detector.py  configurations/EMBER/training/BBDnn/DRS/drs_bbdnn_ember_configuration_file_4096_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/DRS/drs_bbdnn_ember_validation_set_configuration_file_4096_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/DRS/drs_bbdnn_ember_test_set_configuration_file_4096_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/DRS/drs_bbdnn_ember_configuration_file_8192_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/DRS/drs_bbdnn_ember_validation_set_configuration_file_8192_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/DRS/drs_bbdnn_ember_test_set_configuration_file_8192_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/DRS/drs_bbdnn_ember_configuration_file_16384_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/DRS/drs_bbdnn_ember_validation_set_configuration_file_16384_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/DRS/drs_bbdnn_ember_test_set_configuration_file_16384_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/DRS/drs_bbdnn_ember_configuration_file_32768_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/DRS/drs_bbdnn_ember_validation_set_configuration_file_32768_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/DRS/drs_bbdnn_ember_test_set_configuration_file_32768_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/DRS/drs_bbdnn_ember_configuration_file_65536_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/DRS/drs_bbdnn_ember_validation_set_configuration_file_65536_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/DRS/drs_bbdnn_ember_test_set_configuration_file_65536_weighted_1.2.json

# NGramConv
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/DRS/drs_ngramconv_ember_configuration_file_512_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/DRS/drs_ngramconv_ember_validation_set_configuration_file_512_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/DRS/drs_ngramconv_ember_test_set_configuration_file_512_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/DRS/drs_ngramconv_ember_configuration_file_2048_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/DRS/drs_ngramconv_ember_validation_set_configuration_file_2048_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/DRS/drs_ngramconv_ember_test_set_configuration_file_2048_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/DRS/drs_ngramconv_ember_configuration_file_4096_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/DRS/drs_ngramconv_ember_validation_set_configuration_file_4096_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/DRS/drs_ngramconv_ember_test_set_configuration_file_4096_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/DRS/drs_ngramconv_ember_configuration_file_8192_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/DRS/drs_ngramconv_ember_validation_set_configuration_file_8192_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/DRS/drs_ngramconv_ember_test_set_configuration_file_8192_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/DRS/drs_ngramconv_ember_configuration_file_16384_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/DRS/drs_ngramconv_ember_validation_set_configuration_file_16384_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/DRS/drs_ngramconv_ember_test_set_configuration_file_16384_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/DRS/drs_ngramconv_ember_configuration_file_32768_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/DRS/drs_ngramconv_ember_validation_set_configuration_file_32768_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/DRS/drs_ngramconv_ember_test_set_configuration_file_32768_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/DRS/drs_ngramconv_ember_configuration_file_65536_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/DRS/drs_ngramconv_ember_validation_set_configuration_file_65536_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/DRS/drs_ngramconv_ember_test_set_configuration_file_65536_weighted_1.2.json

# MalConv
!'
python train_end2end_detector.py  configurations/EMBER/training/MalConv/DRS/drs_malconv_ember_configuration_file_512_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/DRS/drs_malconv_ember_validation_set_configuration_file_512_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/DRS/drs_malconv_ember_test_set_configuration_file_512_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/DRS/drs_malconv_ember_configuration_file_2048_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/DRS/drs_malconv_ember_validation_set_configuration_file_2048_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/DRS/drs_malconv_ember_test_set_configuration_file_2048_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/DRS/drs_malconv_ember_configuration_file_4096_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/DRS/drs_malconv_ember_validation_set_configuration_file_4096_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/DRS/drs_malconv_ember_test_set_configuration_file_4096_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/DRS/drs_malconv_ember_configuration_file_8192_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/DRS/drs_malconv_ember_validation_set_configuration_file_8192_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/DRS/drs_malconv_ember_test_set_configuration_file_8192_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/DRS/drs_malconv_ember_configuration_file_16384_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/DRS/drs_malconv_ember_validation_set_configuration_file_16384_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/DRS/drs_malconv_ember_test_set_configuration_file_16384_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/DRS/drs_malconv_ember_configuration_file_32768_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/DRS/drs_malconv_ember_validation_set_configuration_file_32768_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/DRS/drs_malconv_ember_test_set_configuration_file_32768_weighted_1.2.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/DRS/drs_malconv_ember_configuration_file_65536_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/DRS/drs_malconv_ember_validation_set_configuration_file_65536_weighted_1.2.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/DRS/drs_malconv_ember_test_set_configuration_file_65536_weighted_1.2.json
'
