cd ../../

python train_ember_lightgbm_detector.py configurations/EMBER/training/LightGBM/lightgbm_configuration_file_lr_0.05_ff_0.7_bf_0.7_pos_weight_0.875.json
python evaluate_ember_lightgbm_detector.py configurations/EMBER/validation/LightGBM/lightgbm_ember_validation_set_configuration_file_lr_0.05_ff_0.7_bf_0.7_pos_weight_0.875.json
python evaluate_ember_lightgbm_detector.py configurations/EMBER/testing/LightGBM/lightgbm_ember_test_set_configuration_file_lr_0.05_ff_0.7_bf_0.7_pos_weight_0.875.json
