cd ../../

# AvastConv
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_configuration_file_0.05.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_validation_set_configuration_file_0.05.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_test_set_configuration_file_0.05.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_configuration_file_0.10.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_validation_set_configuration_file_0.10.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_test_set_configuration_file_0.10.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_configuration_file_0.20.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_validation_set_configuration_file_0.20.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_test_set_configuration_file_0.20.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_configuration_file_0.30.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_validation_set_configuration_file_0.30.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_test_set_configuration_file_0.30.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_configuration_file_0.40.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_validation_set_configuration_file_0.40.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_test_set_configuration_file_0.40.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_configuration_file_0.50.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_validation_set_configuration_file_0.50.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_test_set_configuration_file_0.50.json

# BBDnn
python train_end2end_detector.py  configurations/EMBER/training/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_configuration_file_0.05.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_validation_set_configuration_file_0.05.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_test_set_configuration_file_0.05.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_configuration_file_0.10.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_validation_set_configuration_file_0.10.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_test_set_configuration_file_0.10.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_configuration_file_0.20.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_validation_set_configuration_file_0.20.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_test_set_configuration_file_0.20.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_configuration_file_0.30.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_validation_set_configuration_file_0.30.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_test_set_configuration_file_0.30.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_configuration_file_0.40.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_validation_set_configuration_file_0.40.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_test_set_configuration_file_0.40.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_configuration_file_0.50.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_validation_set_configuration_file_0.50.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_test_set_configuration_file_0.50.json

# NGramConv
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_configuration_file_0.05.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_validation_set_configuration_file_0.05.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_test_set_configuration_file_0.05.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_configuration_file_0.10.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_validation_set_configuration_file_0.10.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_test_set_configuration_file_0.10.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_configuration_file_0.20.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_validation_set_configuration_file_0.20.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_test_set_configuration_file_0.20.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_configuration_file_0.30.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_validation_set_configuration_file_0.30.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_test_set_configuration_file_0.30.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_configuration_file_0.40.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_validation_set_configuration_file_0.40.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_test_set_configuration_file_0.40.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_configuration_file_0.50.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_validation_set_configuration_file_0.50.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_test_set_configuration_file_0.50.json

# MalConv
python train_end2end_detector.py  configurations/EMBER/training/MalConv/Sequential-DRS/sequential_drs_malconv_ember_configuration_file_0.05.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/Sequential-DRS/sequential_drs_malconv_ember_validation_set_configuration_file_0.05.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/Sequential-DRS/sequential_drs_malconv_ember_test_set_configuration_file_0.05.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/Sequential-DRS/sequential_drs_malconv_ember_configuration_file_0.10.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/Sequential-DRS/sequential_drs_malconv_ember_validation_set_configuration_file_0.10.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/Sequential-DRS/sequential_drs_malconv_ember_test_set_configuration_file_0.10.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/Sequential-DRS/sequential_drs_malconv_ember_configuration_file_0.20.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/Sequential-DRS/sequential_drs_malconv_ember_validation_set_configuration_file_0.20.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/Sequential-DRS/sequential_drs_malconv_ember_test_set_configuration_file_0.20.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/Sequential-DRS/sequential_drs_malconv_ember_configuration_file_0.30.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/Sequential-DRS/sequential_drs_malconv_ember_validation_set_configuration_file_0.30.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/Sequential-DRS/sequential_drs_malconv_ember_test_set_configuration_file_0.30.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/Sequential-DRS/sequential_drs_malconv_ember_configuration_file_0.40.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/Sequential-DRS/sequential_drs_malconv_ember_validation_set_configuration_file_0.40.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/Sequential-DRS/sequential_drs_malconv_ember_test_set_configuration_file_0.40.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/Sequential-DRS/sequential_drs_malconv_ember_configuration_file_0.50.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/Sequential-DRS/sequential_drs_malconv_ember_validation_set_configuration_file_0.50.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/Sequential-DRS/sequential_drs_malconv_ember_test_set_configuration_file_0.50.json

