cd ../../

# AvastConv
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/avastconv_ember_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/avastconv_ember_validation_set_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/avastconv_ember_test_set_configuration_file_pos_weight_0.875.json

#RS-AvastConv
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/rs_avastconv_ember_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/rs_avastconv_ember_validation_set_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/rs_avastconv_ember_test_set_configuration_file_pos_weight_0.875.json

#RsDel-AvastConv
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/rsdel_avastconv_ember_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/rsdel_avastconv_ember_validation_set_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/rsdel_avastconv_ember_test_set_configuration_file_pos_weight_0.875.json
