cd ../../

!'
# ResNet18
python train_end2end_detector.py  configurations/EMBER/training/ResNet18/resnet18_ember_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/ResNet18/resnet18_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/ResNet18/resnet18_ember_test_set_configuration_file.json



# AvastConv
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/avastconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/rs_avastconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/rsdel_avastconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/drs_avastconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/sequential_drs_avastconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/random_drs_avastconv_ember_configuration_file.json
'
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/avastconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/rs_avastconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/rsdel_avastconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/drs_avastconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/sequential_drs_avastconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/random_drs_avastconv_ember_validation_set_configuration_file.json

python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/avastconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/rs_avastconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/rsdel_avastconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/drs_avastconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/sequential_drs_avastconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/random_drs_avastconv_ember_test_set_configuration_file.json

!'
# BBDnn
python train_end2end_detector.py  configurations/EMBER/training/BBDnn/bbdnn_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/BBDnn/rs_bbdnn_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/BBDnn/rsdel_bbdnn_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/BBDnn/drs_bbdnn_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/BBDnn/sequential_drs_bbdnn_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/BBDnn/random_drs_bbdnn_ember_configuration_file.json

python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/bbdnn_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/rs_bbdnn_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/rsdel_bbdnn_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/drs_bbdnn_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/sequential_drs_bbdnn_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/random_drs_bbdnn_ember_validation_set_configuration_file.json

python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/bbdnn_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/rs_bbdnn_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/rsdel_bbdnn_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/drs_bbdnn_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/sequential_drs_bbdnn_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/random_drs_bbdnn_ember_test_set_configuration_file.json

# NGramConv
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/ngramconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/rs_ngramconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/rsdel_ngramconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/drs_ngramconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/sequential_drs_ngramconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/random_drs_ngramconv_ember_configuration_file.json

python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/ngramconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/rs_ngramconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/rsdel_ngramconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/drs_ngramconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/sequential_drs_ngramconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/random_drs_ngramconv_ember_validation_set_configuration_file.json

python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/ngramconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/rs_ngramconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/rsdel_ngramconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/drs_ngramconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/sequential_drs_ngramconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/random_drs_ngramconv_ember_test_set_configuration_file.json

# MalConv
python train_end2end_detector.py  configurations/EMBER/training/MalConv/malconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/MalConv/rs_malconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/MalConv/rsdel_malconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/MalConv/drs_malconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/MalConv/sequential_drs_malconv_ember_configuration_file.json
python train_end2end_detector.py  configurations/EMBER/training/MalConv/random_drs_malconv_ember_configuration_file.json

python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/malconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/rs_malconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/rsdel_malconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/drs_malconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/sequential_drs_malconv_ember_validation_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/random_drs_malconv_ember_validation_set_configuration_file.json

python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/malconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/rs_malconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/rsdel_malconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/drs_malconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/sequential_drs_malconv_ember_test_set_configuration_file.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/random_drs_malconv_ember_test_set_configuration_file.json
'