cd ../../

!'
# AvastConv
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/rsdel_avastconv_ember_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/rsdel_avastconv_ember_validation_set_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/rsdel_avastconv_ember_test_set_configuration_file_pos_weight_0.875.json

# BBDnn
python train_end2end_detector.py  configurations/EMBER/training/BBDnn/rsdel_bbdnn_ember_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/rsdel_bbdnn_ember_validation_set_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/rsdel_bbdnn_ember_test_set_configuration_file_pos_weight_0.875.json

# NGramConv
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/rsdel_ngramconv_ember_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/rsdel_ngramconv_ember_validation_set_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/rsdel_ngramconv_ember_test_set_configuration_file_pos_weight_0.875.json


# MalConv
python train_end2end_detector.py  configurations/EMBER/training/MalConv/rsdel_malconv_ember_configuration_file_pos_weight_0.875.json
'
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/rsdel_malconv_ember_validation_set_configuration_file_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/rsdel_malconv_ember_test_set_configuration_file_pos_weight_0.875.json