cd ../../

# AvastConv
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_configuration_file_0.05_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_validation_set_configuration_file_0.05_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_test_set_configuration_file_0.05_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_configuration_file_0.10_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_validation_set_configuration_file_0.10_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_test_set_configuration_file_0.10_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_configuration_file_0.20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_validation_set_configuration_file_0.20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/Sequential-DRS/sequential_drs_avastconv_ember_test_set_configuration_file_0.20_pos_weight_0.875.json

# BBDnn
#python train_end2end_detector.py  configurations/EMBER/training/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_configuration_file_0.05_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_validation_set_configuration_file_0.05_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_test_set_configuration_file_0.05_pos_weight_0.875.json

#python train_end2end_detector.py  configurations/EMBER/training/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_configuration_file_0.10_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_validation_set_configuration_file_0.10_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_test_set_configuration_file_0.10_pos_weight_0.875.json

#python train_end2end_detector.py  configurations/EMBER/training/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_configuration_file_0.20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_validation_set_configuration_file_0.20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/Sequential-DRS/sequential_drs_bbdnn_ember_test_set_configuration_file_0.20_pos_weight_0.875.json

# NGramConv
#python train_end2end_detector.py  configurations/EMBER/training/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_configuration_file_0.05_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_validation_set_configuration_file_0.05_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_test_set_configuration_file_0.05_pos_weight_0.875.json

#python train_end2end_detector.py  configurations/EMBER/training/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_configuration_file_0.10_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_validation_set_configuration_file_0.10_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_test_set_configuration_file_0.10_pos_weight_0.875.json

#python train_end2end_detector.py  configurations/EMBER/training/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_configuration_file_0.20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_validation_set_configuration_file_0.20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/Sequential-DRS/sequential_drs_ngramconv_ember_test_set_configuration_file_0.20_pos_weight_0.875.json


# MalConv
#python train_end2end_detector.py  configurations/EMBER/training/MalConv/Sequential-DRS/sequential_drs_malconv_ember_configuration_file_0.05_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/Sequential-DRS/sequential_drs_malconv_ember_validation_set_configuration_file_0.05_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/Sequential-DRS/sequential_drs_malconv_ember_test_set_configuration_file_0.05_pos_weight_0.875.json

#python train_end2end_detector.py  configurations/EMBER/training/MalConv/Sequential-DRS/sequential_drs_malconv_ember_configuration_file_0.10_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/Sequential-DRS/sequential_drs_malconv_ember_validation_set_configuration_file_0.10_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/Sequential-DRS/sequential_drs_malconv_ember_test_set_configuration_file_0.10_pos_weight_0.875.json

#python train_end2end_detector.py  configurations/EMBER/training/MalConv/Sequential-DRS/sequential_drs_malconv_ember_configuration_file_0.20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/Sequential-DRS/sequential_drs_malconv_ember_validation_set_configuration_file_0.20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/Sequential-DRS/sequential_drs_malconv_ember_test_set_configuration_file_0.20_pos_weight_0.875.json

