cd ../../


# AvastConv
python train_end2end_detector.py  configurations/EMBER/training/AvastConv/DRSM/drsm_avastconv_ember_configuration_file_4_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/DRSM/drsm_avastconv_ember_validation_set_configuration_file_4_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/DRSM/drsm_avastconv_ember_test_set_configuration_file_4_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/DRSM/drsm_avastconv_ember_configuration_file_8_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/DRSM/drsm_avastconv_ember_validation_set_configuration_file_8_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/DRSM/drsm_avastconv_ember_test_set_configuration_file_8_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/DRSM/drsm_avastconv_ember_configuration_file_12_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/DRSM/drsm_avastconv_ember_validation_set_configuration_file_12_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/DRSM/drsm_avastconv_ember_test_set_configuration_file_12_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/DRSM/drsm_avastconv_ember_configuration_file_16_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/DRSM/drsm_avastconv_ember_validation_set_configuration_file_16_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/DRSM/drsm_avastconv_ember_test_set_configuration_file_16_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/AvastConv/DRSM/drsm_avastconv_ember_configuration_file_20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/AvastConv/DRSM/drsm_avastconv_ember_validation_set_configuration_file_20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/AvastConv/DRSM/drsm_avastconv_ember_test_set_configuration_file_20_pos_weight_0.875.json


# BBDnn
python train_end2end_detector.py  configurations/EMBER/training/BBDnn/DRSM/drsm_bbdnn_ember_configuration_file_4_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/DRSM/drsm_bbdnn_ember_validation_set_configuration_file_4_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/DRSM/drsm_bbdnn_ember_test_set_configuration_file_4_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/DRSM/drsm_bbdnn_ember_configuration_file_8_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/DRSM/drsm_bbdnn_ember_validation_set_configuration_file_8_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/DRSM/drsm_bbdnn_ember_test_set_configuration_file_8_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/DRSM/drsm_bbdnn_ember_configuration_file_12_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/DRSM/drsm_bbdnn_ember_validation_set_configuration_file_12_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/DRSM/drsm_bbdnn_ember_test_set_configuration_file_12_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/DRSM/drsm_bbdnn_ember_configuration_file_16_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/DRSM/drsm_bbdnn_ember_validation_set_configuration_file_16_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/DRSM/drsm_bbdnn_ember_test_set_configuration_file_16_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/BBDnn/DRSM/drsm_bbdnn_ember_configuration_file_20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/BBDnn/DRSM/drsm_bbdnn_ember_validation_set_configuration_file_20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/BBDnn/DRSM/drsm_bbdnn_ember_test_set_configuration_file_20_pos_weight_0.875.json


# NGramConv
python train_end2end_detector.py  configurations/EMBER/training/NGramConv/DRSM/drsm_ngramconv_ember_configuration_file_4_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/DRSM/drsm_ngramconv_ember_validation_set_configuration_file_4_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/DRSM/drsm_ngramconv_ember_test_set_configuration_file_4_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/DRSM/drsm_ngramconv_ember_configuration_file_8_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/DRSM/drsm_ngramconv_ember_validation_set_configuration_file_8_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/DRSM/drsm_ngramconv_ember_test_set_configuration_file_8_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/DRSM/drsm_ngramconv_ember_configuration_file_12_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/DRSM/drsm_ngramconv_ember_validation_set_configuration_file_12_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/DRSM/drsm_ngramconv_ember_test_set_configuration_file_12_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/DRSM/drsm_ngramconv_ember_configuration_file_16_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/DRSM/drsm_ngramconv_ember_validation_set_configuration_file_16_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/DRSM/drsm_ngramconv_ember_test_set_configuration_file_16_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/NGramConv/DRSM/drsm_ngramconv_ember_configuration_file_20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/NGramConv/DRSM/drsm_ngramconv_ember_validation_set_configuration_file_20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/NGramConv/DRSM/drsm_ngramconv_ember_test_set_configuration_file_20_pos_weight_0.875.json


# MalConv
python train_end2end_detector.py  configurations/EMBER/training/MalConv/DRSM/drsm_malconv_ember_configuration_file_4_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/DRSM/drsm_malconv_ember_validation_set_configuration_file_4_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/DRSM/drsm_malconv_ember_test_set_configuration_file_4_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/DRSM/drsm_malconv_ember_configuration_file_8_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/DRSM/drsm_malconv_ember_validation_set_configuration_file_8_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/DRSM/drsm_malconv_ember_test_set_configuration_file_8_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/DRSM/drsm_malconv_ember_configuration_file_12_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/DRSM/drsm_malconv_ember_validation_set_configuration_file_12_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/DRSM/drsm_malconv_ember_test_set_configuration_file_12_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/DRSM/drsm_malconv_ember_configuration_file_16_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/DRSM/drsm_malconv_ember_validation_set_configuration_file_16_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/DRSM/drsm_malconv_ember_test_set_configuration_file_16_pos_weight_0.875.json

python train_end2end_detector.py  configurations/EMBER/training/MalConv/DRSM/drsm_malconv_ember_configuration_file_20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/validation/MalConv/DRSM/drsm_malconv_ember_validation_set_configuration_file_20_pos_weight_0.875.json
python evaluate_end2end_detector.py  configurations/EMBER/testing/MalConv/DRSM/drsm_malconv_ember_test_set_configuration_file_20_pos_weight_0.875.json
'
