cd ../../../
cd evaluators

python generate_metrics_file.py ../output/EMBER-AvastConv-512000-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-AvastConv-512000-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-BBDnn-102400-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-BBDnn-102400-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-AvastConv-10244-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-AvastConv-10244-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-AvastConv-16384-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-AvastConv-16384-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-AvastConv-32768-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-AvastConv-32768-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-AvastConv-65536-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-AvastConv-65536-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-AvastConv-131072-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-AvastConv-131072-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-BBDnn-4096-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-BBDnn-4096-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-BBDnn-8192-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-BBDnn-8192-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-BBDnn-16384-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-BBDnn-16384-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-BBDnn-32768-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-BBDnn-32768-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-BBDnn-65536-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-BBDnn-65536-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-BBDnn-131072-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-BBDnn-131072-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-MalConv-512-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-MalConv-512-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-MalConv-2048-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-MalConv-2048-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-MalConv-4096-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-MalConv-4096-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-MalConv-8192-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-MalConv-8192-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-MalConv-16384-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-MalConv-16384-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-MalConv-32768-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-MalConv-32768-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-MalConv-65536-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-MalConv-65536-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-MalConv-131072-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-MalConv-131072-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-NGramConv-512-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-NGramConv-512-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-NGramConv-2048-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-NGramConv-2048-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-NGramConv-4096-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-NGramConv-4096-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-NGramConv-8192-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-NGramConv-8192-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-NGramConv-16384-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-NGramConv-16384-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-NGramConv-32768-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-NGramConv-32768-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-NGramConv-65536-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-NGramConv-65536-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-F-DRS-NGramConv-131072-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-F-DRS-NGramConv-131072-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-AvastConv-4-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-AvastConv-4-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-AvastConv-8-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-AvastConv-8-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-AvastConv-12-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-AvastConv-12-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-AvastConv-16-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-AvastConv-16-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-AvastConv-20-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-AvastConv-20-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-BBDnn-4-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-BBDnn-4-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-BBDnn-8-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-BBDnn-8-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-BBDnn-12-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-BBDnn-12-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-BBDnn-16-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-BBDnn-16-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-BBDnn-20-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-BBDnn-20-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-MalConv-4-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-MalConv-4-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-MalConv-8-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-MalConv-8-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-MalConv-12-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-MalConv-12-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-MalConv-16-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-MalConv-16-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-MalConv-20-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-MalConv-20-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-NGramConv-4-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-NGramConv-4-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-NGramConv-8-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-NGramConv-8-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-NGramConv-12-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-NGramConv-12-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-NGramConv-16-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-NGramConv-16-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-K-DRS-NGramConv-20-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-K-DRS-NGramConv-20-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-LightGBM/EMBER_test_set_scores.csv ../output/EMBER-LightGBM/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-MalConv-2000000-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-MalConv-2000000-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-NGramConv-512000-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-NGramConv-512000-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Random-DRS-AvastConv-0.05-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Random-DRS-AvastConv-0.05-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Random-DRS-AvastConv-0.10-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Random-DRS-AvastConv-0.10-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Random-DRS-AvastConv-0.20-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Random-DRS-AvastConv-0.20-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Random-DRS-BBDnn-0.05-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Random-DRS-BBDnn-0.05-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Random-DRS-BBDnn-0.10-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Random-DRS-BBDnn-0.10-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Random-DRS-BBDnn-0.20-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Random-DRS-BBDnn-0.20-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Random-DRS-MalConv-0.05-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Random-DRS-MalConv-0.05-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Random-DRS-MalConv-0.10-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Random-DRS-MalConv-0.10-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Random-DRS-MalConv-0.20-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Random-DRS-MalConv-0.20-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Random-DRS-NGramConv-0.05-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Random-DRS-NGramConv-0.05-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Random-DRS-NGramConv-0.10-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Random-DRS-NGramConv-0.10-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Random-DRS-NGramConv-0.20-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Random-DRS-NGramConv-0.20-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-ResNet18-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-ResNet18-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-RS-AvastConv-512000-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-RS-AvastConv-512000-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-RS-BBDnn-102400-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-RS-BBDnn-102400-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-RS-MalConv-2000000-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-RS-MalConv-2000000-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-RS-NGramConv-512000-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-RS-NGramConv-512000-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-RsDel-AvastConv-512000-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-RsDel-AvastConv-512000-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-RsDel-BBDnn-102400-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-RsDel-BBDnn-102400-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-RsDel-MalConv-2000000-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-RsDel-MalConv-2000000-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-RsDel-NGramConv-512000-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-RsDel-NGramConv-512000-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Sequential-DRS-AvastConv-0.05-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Sequential-DRS-AvastConv-0.05-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Sequential-DRS-AvastConv-0.10-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Sequential-DRS-AvastConv-0.10-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Sequential-DRS-AvastConv-0.20-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Sequential-DRS-AvastConv-0.20-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Sequential-DRS-BBDnn-0.05-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Sequential-DRS-BBDnn-0.05-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Sequential-DRS-BBDnn-0.10-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Sequential-DRS-BBDnn-0.10-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Sequential-DRS-BBDnn-0.20-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Sequential-DRS-BBDnn-0.20-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Sequential-DRS-MalConv-0.05-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Sequential-DRS-MalConv-0.05-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Sequential-DRS-MalConv-0.10-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Sequential-DRS-MalConv-0.10-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Sequential-DRS-MalConv-0.20-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Sequential-DRS-MalConv-0.20-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Sequential-DRS-NGramConv-0.05-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Sequential-DRS-NGramConv-0.05-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Sequential-DRS-NGramConv-0.10-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Sequential-DRS-NGramConv-0.10-pos-weight-0.875/EMBER_test_set_results.csv
python generate_metrics_file.py ../output/EMBER-Sequential-DRS-NGramConv-0.20-pos-weight-0.875/EMBER_test_set_scores.csv ../output/EMBER-Sequential-DRS-NGramConv-0.20-pos-weight-0.875/EMBER_test_set_results.csv


